<?php
/** @var $block \Magento\Framework\View\Element\Template */
// Header is sticky up to medium
$class = 'sticky top-0 lg:relative lg:top-auto';

// Header is sticky in desktop view as well
// $class = 'sticky top-0';

if ($additionalClasses = $block->getClass()) {
    $class .= ' ' . $additionalClasses;
}
?>
<div x-data="stickyHeader()" class="z-50 transition ease-in-out transform-gpu lg:translate-y-0 <?= $class ?>" :class="stickyClass" @scroll.window.debounce="scroll">
<?= $block->getChildHtml() ?>
</div>
<script>
function stickyHeader() {
    return {
        lastOffset: 0,
        isHidden: false,
        stickyClass: '',
        scroll() {
            let offset = window.pageYOffset,
                isStuck = this.$el.offsetTop - this.$el.scrollHeight;
            this.isHidden = offset > this.lastOffset;
            this.lastOffset = offset;
            this.stickyClass = (isStuck > 0 ? '<?= $block->getStickyClass() ?>' : '');
        }
    }
}
</script>