<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Checkout\Block\Cart\Sidebar as SidebarCart;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(SidebarCart::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
?>
<?php if ($showMiniCart): ?>
    <button
<?php else: ?>
<a
    <?php endif ?>
    x-data="initCartButton()"
    id="menu-cart-icon"
    class="relative inline-block rounded p-1 hover:bg-primary/10 outline-offset-2"
    x-ref="cartButton"
    @private-content-loaded.window="getData(event.detail.data)"
    :aria-disabled="isCartEmpty()"
    :aria-label="`<?= $escaper->escapeHtmlAttr($showMiniCart ? __('Toggle minicart') : __('View cart')) ?>,
        ${isCartEmpty()
            ? '<?= $escaper->escapeHtmlAttr(__('Cart is empty')) ?>'
            : cart.summary_count > 1
                ? hyva.str('<?= $escaper->escapeHtmlAttr(__('%1 items')) ?>', cart.summary_count)
                : hyva.str('<?= $escaper->escapeHtmlAttr(__('%1 item')) ?>', cart.summary_count)
        }`"
    <?php if ($showMiniCart): ?>
        @click.prevent.stop="() => {
        $dispatch('toggle-cart', { isOpen: true })
    }"
        <?php /*@toggle-cart.window="toggleCart($event)"*/ ?>
        :aria-expanded="drawerState('hyva-cart-drawer')"
        aria-haspopup="dialog"
        @click="drawerOpen('hyva-cart-drawer')"
    <?php else: ?>
        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
        title="<?= $escaper->escapeHtmlAttr(__('View cart')) ?>"
    <?php endif ?>
>
    <?= $heroicons->shoppingCartHtml("md:h-6 md:w-6", 28, 28, ["aria-hidden" => "true"]) ?>
    <span
        x-text="cart.summary_count"
        x-show="!isCartEmpty()"
        x-cloak
        class="absolute -top-1.5 -right-1.5 h-5 px-2 py-1 rounded-full bg-primary text-white
                        text-xs font-semibold leading-none text-center uppercase tabular-nums"
        aria-hidden="true"></span>
    <?php if ($showMiniCart): ?>
        </button>
    <?php else: ?>
</a>
<?php endif ?>
<script>
    /**
     * Taken from initHeader()
     * The button's functionality should not rely on the fact that it is a descendant of
     * the header element. It should function independently.
     */
    function initCartButton() {
        return {
            cart: {},
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            },
            isCartEmpty() {
                return !this.cart.summary_count
            }
        }
    }
</script>
